// Code generated by "stringer -type token -linecomment tokens.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftParen-1]
	_ = x[RightParen-2]
	_ = x[LeftBrace-3]
	_ = x[RightBrace-4]
	_ = x[Comma-5]
	_ = x[Dot-6]
	_ = x[Minus-7]
	_ = x[Plus-8]
	_ = x[Semicolon-9]
	_ = x[Colon-10]
	_ = x[Question-11]
	_ = x[Slash-12]
	_ = x[Star-13]
	_ = x[Bang-14]
	_ = x[BangEqual-15]
	_ = x[Equal-16]
	_ = x[EqualEqual-17]
	_ = x[Greater-18]
	_ = x[GreaterEqual-19]
	_ = x[Less-20]
	_ = x[LessEqual-21]
	_ = x[Identifier-22]
	_ = x[String-23]
	_ = x[Number-24]
	_ = x[And-25]
	_ = x[Break-26]
	_ = x[Class-27]
	_ = x[Continue-28]
	_ = x[Else-29]
	_ = x[False-30]
	_ = x[Fun-31]
	_ = x[For-32]
	_ = x[If-33]
	_ = x[Nil-34]
	_ = x[Or-35]
	_ = x[Print-36]
	_ = x[Return-37]
	_ = x[Super-38]
	_ = x[This-39]
	_ = x[True-40]
	_ = x[Var-41]
	_ = x[While-42]
	_ = x[EOF-43]
}

const _token_name = "(){},.-+;:?/*!!====>>=<<=identstringnumberandbreakclasscontinueelsefalsefunforifnilorprintreturnsuperthistruevarwhileeof"

var _token_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 20, 22, 23, 25, 30, 36, 42, 45, 50, 55, 63, 67, 72, 75, 78, 80, 83, 85, 90, 96, 101, 105, 109, 112, 117, 120}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
