// Code generated by "stringer -type token -linecomment tokens.go"; DO NOT EDIT.

package main

import "strconv"

const _token_name = "(){},.-+;/*!!====>>=<<=identstringnumberandclasselsefalsefunforifnilorprintreturnsuperthistruevarwhileeof"

var _token_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 17, 18, 20, 21, 23, 28, 34, 40, 43, 48, 52, 57, 60, 63, 65, 68, 70, 75, 81, 86, 90, 94, 97, 102, 105}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
